
server:
  port: 8081

dubbo:
  application:
    name: pikachu-crontab-dubbo-consumer
  registry:
    id: zookeeper
    address: zookeeper://${ZK_HOST}:${ZK_PORT}

spring:
  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    userName: ${MQ_USERNAME}
    passWord: ${MQ_PASSWORD}
    virtualHost: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5
        prefetch: 5
        acknowledge-mode: manual