spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  application:
    name: pikachu-article-dubbo-provider
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

redisson:
  sentinel-addresses: redis://${REDIS_SENTINEL_HOST}:${REDIS_SENTINEL_PORT}
  password: ${REDIS_PASSWORD}
  master-name: ${REDIS_SENTINEL_MASTER_NAME}

dubbo:
  application:
    name: pikachu-article-dubbo-provider
    qos-port: ${DUBBO_QOS_PORT}
  protocol:
    id: dubbo
    name: dubbo
    port: ${DUBBO_PORT}
    status: server
  registry:
    id: zookeeper
    address: zookeeper://${ZK_HOST}:${ZK_PORT}
  scan:
    basePackages: >
      com.huiaong.pikachu.article.impl.service,
      com.huiaong.pikachu.article.impl.producer


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.pikachu.article.model
