spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  application:
    name: pikachu-log-dubbo-provider

dubbo:
  application:
    name: pikachu-log-dubbo-provider
    qos-port: ${DUBBO_QOS_PORT}
  protocol:
    id: dubbo
    name: dubbo
    port: ${DUBBO_APP_PORT}
    status: server
  registry:
    id: zookeeper
    address: zookeeper://${ZK_HOST}:${ZK_PORT}
  scan:
    basePackages: >
      com.huiaong.pikachu.log.impl.*.service,
      com.huiaong.pikachu.log.impl.*.producer


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.pikachu.log.order.model,
    com.huiaong.pikachu.log.sms.model
