
server:
  port: 8082

dubbo:
  application:
    name: pikachu-receiver-dubbo-consumer
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181

spring:
  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    userName: ${MQ_USERNAME}
    passWord: ${MQ_PASSWORD}
    virtualHost: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5
        prefetch: 5
        acknowledge-mode: manual