
server:
  port: 8080

dubbo:
  scan:
    basePackages: >
      com.huiaong.pikachu.admin.order.controller
  application:
    name: pikachu-admin-dubbo-consumer
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
