
server:
  port: 8080

dubbo:
  application:
    name: pikachu-admin-dubbo-consumer
  registry:
    id: zookeeper
    address: zookeeper://${ZK_HOST}:${ZK_PORT}

logging:
  level:
    com.huiaong.pikachu.web.core.logging: DEBUG