spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  application:
    name: pikachu-item-dubbo-provider

redisson:
  sentinel-addresses: redis://${REDIS_SENTINEL_HOST}:${REDIS_SENTINEL_PORT}
  password: ${REDIS_PASSWORD}
  master-name: ${REDIS_SENTINEL_MASTER_NAME}

dubbo:
  application:
    name: pikachu-item-dubbo-provider
    qos-port: ${DUBBO_QOS_PORT}
  protocol:
    id: dubbo
    name: dubbo
    port: ${DUBBO_APP_PORT}
    status: server
  registry:
    id: zookeeper
    address: zookeeper://${ZK_HOST}:${ZK_PORT}
  scan:
    basePackages: >
      com.huiaong.pikachu.item.impl.goods.service,
      com.huiaong.pikachu.item.impl.cart.service


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.pikachu.item.cart.model,
    com.huiaong.pikachu.item.goods.model
