spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pikachu?useUnicode=true&characterEncoding=UTF8
    username: 'root'
    password: 'root'
  application:
    name: pikachu-trade-dubbo-provider

logging:
  level:
    com.huiaong.pikachu.trade.impl.dao: DEBUG

dubbo:
  application:
    name: pikachu-trade-dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: >
      com.huiaong.pikachu.trade.impl.service,
      com.huiaong.pikachu.trade.impl.producer


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.pikachu.trade.(mq).model
